# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpuautoscaler < Formula
  desc "Kubernetes-native GPU Autoscaler: maximize utilization, minimize cloud costs"
  homepage "https://github.com/holynakamoto/gpuautoscaler"
  version "1.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/holynakamoto/gpuautoscaler/releases/download/v1.4.0/gpuautoscaler_Darwin_x86_64.tar.gz"
      sha256 "9e801a8f8ccbdf8d48049aa3ca3110a4d655ceb46e6edf35a34a3a59729359f1"

      def install
        bin.install "gpu-autoscaler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/holynakamoto/gpuautoscaler/releases/download/v1.4.0/gpuautoscaler_Darwin_arm64.tar.gz"
      sha256 "ff84994cea64f7f00290569c6bd987da88c5a124b8aa38d7dd61c2956795baad"

      def install
        bin.install "gpu-autoscaler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/holynakamoto/gpuautoscaler/releases/download/v1.4.0/gpuautoscaler_Linux_x86_64.tar.gz"
      sha256 "a87f048d5324f5ee512de4501db533ff45499ff61671bdd56045ba45b50b5826"
      def install
        bin.install "gpu-autoscaler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/holynakamoto/gpuautoscaler/releases/download/v1.4.0/gpuautoscaler_Linux_arm64.tar.gz"
      sha256 "406a51c2194ca0c289370118bf760fcfdb14e3873910e0053659f0306e927f8a"
      def install
        bin.install "gpu-autoscaler"
      end
    end
  end

  test do
    system "#{bin}/gpu-autoscaler", "version"
  end
end
