# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gpuautoscaler < Formula
  desc "Kubernetes-native GPU Autoscaler: maximize utilization, minimize cloud costs"
  homepage "https://github.com/holynakamoto/gpuautoscaler"
  version "1.3.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/holynakamoto/gpuautoscaler/releases/download/v1.3.3/gpuautoscaler_Darwin_x86_64.tar.gz"
      sha256 "baaf179d239daeb0c96fe8b2b967aded23b06d024974513a6e95800577ba5cf1"

      def install
        bin.install "gpu-autoscaler"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/holynakamoto/gpuautoscaler/releases/download/v1.3.3/gpuautoscaler_Darwin_arm64.tar.gz"
      sha256 "ff2a4a320744a806767b2c1757e3a3fba1546aca0d4cf4620283c00f46f5df06"

      def install
        bin.install "gpu-autoscaler"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/holynakamoto/gpuautoscaler/releases/download/v1.3.3/gpuautoscaler_Linux_x86_64.tar.gz"
      sha256 "ec06aeb68fa239769432711edbc1db901e64c18f0d66a9aeed54704051a5fa8c"
      def install
        bin.install "gpu-autoscaler"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/holynakamoto/gpuautoscaler/releases/download/v1.3.3/gpuautoscaler_Linux_arm64.tar.gz"
      sha256 "e3c5074055705121a3cfcafc2d18301dd71d98e6e67794f5dae1631907e467b3"
      def install
        bin.install "gpu-autoscaler"
      end
    end
  end

  test do
    system "#{bin}/gpu-autoscaler", "version"
  end
end
